apiVersion: v1
kind: Service
metadata:
  name: java-web-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8100
    protocol: TCP
  selector:
    app: java-web-app
